config/routes.rb
Rails.application.routes.draw do
  resources :oneclicks
  resources :webpays
  resources :credit_cards
  resources :transbanks
  resources :payments
  resources :orders
  resources :paypals
  resources :stripes
  resources :images
  resources :physicals
  resources :digitals
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
    has_many  :transbanks, as: :category
end

app/models/digital.rb
class Digital < ApplicationRecord
  has_many  :products, as: :category
  has_one :image, as: :imageable
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  has_one_attached :photo
end

app/models/oneclick.rb
class Oneclick < ApplicationRecord
    has_many  :transbanks, as: :category
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items, dependent: :destroy
    has_many :products, through: :order_items
    has_one :payment

    def add_product(product_id, quantity)
        product = Product.find(product_id)
        if product
            order_items.create(product_id: product.id, quantity: quantity, price: product.price)
            compute_total
        end
    end
    
    def compute_total
        sum = 0
        order_items.each do |item|
            sum += item.price
        end
        update_attribute(:total, sum)
    end
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :category, polymorphic: true
    belongs_to :order, dependent: :destroy
end

app/models/paypal.rb
class Paypal < ApplicationRecord
    has_many  :payments, as: :category
end

app/models/physical.rb
class Physical < ApplicationRecord
  has_many  :products, as: :category
  has_many :images, as: :imageable
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category, polymorphic: true
  has_many :order_items
  has_many :orders, through: :order_items
end

app/models/stripe.rb
class Stripe < ApplicationRecord
    has_many  :payments, as: :category
end

app/models/transbank.rb
class Transbank < ApplicationRecord
    belongs_to :category, polymorphic: true
end

app/models/webpay.rb
class Webpay < ApplicationRecord
    has_many  :transbanks, as: :category
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def credit_card_params
      params.fetch(:credit_card, {})
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/helpers/digitals_helper.rb
module DigitalsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/oneclicks_helper.rb
module OneclicksHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/paypals_helper.rb
module PaypalsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/stripes_helper.rb
module StripesHelper
end

app/helpers/webpays_helper.rb
module WebpaysHelper
end

app/views/credit_cards/_form.html.erb
<%= form_with(model: credit_card, local: true) do |form| %>
  <% if credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<h1>Editing Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Show', @credit_card %> |
<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Credit Cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @credit_cards.each do |credit_card| %>
      <tr>
        <td><%= link_to 'Show', credit_card %></td>
        <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
        <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Credit Card', new_credit_card_path %>

app/views/credit_cards/new.html.erb
<h1>New Credit Card</h1>

<%= render 'form', credit_card: @credit_card %>

<%= link_to 'Back', credit_cards_path %>

app/views/credit_cards/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
<%= link_to 'Back', credit_cards_path %>